feat(Cache): add `setValue` combinator.
Effect-TS/cache pull request #11
Opened 2022-01-01 15:19 UTC by patroza

2022-01-01 16:35 UTC, IMax153 requested changes

2022-01-01 16:35 UTC, IMax153 commented on packages/cache/src/Cache/index.ts
> +export function setValue_<Key, Error, Value>(
We should also add the data last combinator, i.e.

```typescript
export function setValue<Key, Value>(key: Key, value: Value) {
  return <Error>(self: Cache<Key, Error, Value>): T.UIO<void> => setValue_(self, key, value)
}
```

2022-01-01 16:36 UTC, IMax153 commented
Also looks like a similar issue with `prettier` formatting in CI-CD. Not sure why your VSCode isn't auto-formatting 🤔

2022-01-03 09:13 UTC, patroza commented on packages/cache/src/Cache/index.ts
> +export function setValue_<Key, Error, Value>(
Alrighty

2022-01-03 09:18 UTC, patroza commented
@IMax153 ready for the next review.
tests and data-last added.

2022-01-03 09:39 UTC, patroza commented
> Also looks like a similar issue with `prettier` formatting in CI-CD. Not sure why your VSCode isn't auto-formatting 🤔

apparently im used to having my formatter settings in the repository `.vscode/settings.json`.
I made em global user settings now ;-)

2022-01-03 14:13 UTC, IMax153 approved these changes
LGTM 👍 - thanks for your work on this.

2022-01-03 14:13 UTC, IMax153 commented
> apparently im used to having my formatter settings in the repository `.vscode/settings.json`

This is a good point - I'll add to the `.vscode/settings.json` 👍

2022-01-03 14:30 UTC, merged